### ISSUE TITLE
Graphics Issue

### ISSUE THREAD

**Issue by paalwilliams** [JPyke3/mbp-manjaro#4] opened 2020-08-10 02:20 UTC
Hi there,

running into an issue where the display seems to be cutting out about 10 seconds into the installer. This happens at:

[ OK ] Started Load/Save RF Kill Switch Status Match

I know there was a similar issue on the [arch-mpb gist,](https://gist.github.com/TRPB/437f663b545d23cc8a2073253c774be3#gistcomment-3296174) related to the amd graphics, so perhaps this is related.

The touch bar turns on about 3seconds after the display cuts out, so it seems like the installation process is still running, just no graphics.

I'm using the efi=noruntime boot flag.
Latest manjaro KDE mbp ISO burned to Flash drive using balenaetcher
2018 Macbook Pro 2.6 GHz 6-Core Intel Core i7 
Radio Pro 560x

**Comment by paalwilliams** [comment] 2020-08-10 02:39
Update: adding module_blacklist=amdgpu seems to solve this. will post updates as I go.

**Comment by JPyke3** [comment] 2020-08-10 04:42
Hi there, Thanks for posting the issue!

By the sounds of things you are in fact on the right track, it seems to be an issue with the gpu on your machine. After blacklisting the gpu drivers, is it possible to switch to another TTY console? If you have an external keyboard try pressing `ctl` + `alt` + `f3`. Then you can check dmesg to potentially debug the issue. 

Another thing to note, is that when the system boots into anything except for MacOS, Macs disable the integrated graphics card if it detects another gpu. I would assume if you are disabling `amdgpu` it could be disabling the only graphics card your machine is running. Just a thing to note. 

Unfortunatley, I do not have a MacBook with a dedicated gpu. So I can't test this on my end. Hope my comment can point you on the right track.

**Comment by JPyke3** [comment] 2020-08-12 20:49
Going to close this issue as there hasn't been a response for a little bit. Feel free to open the issue again any time :)

**Comment by mpfaff** [comment] 2020-08-26 03:59
@JPyke3 I had the same issue and got stuck at the same spot as him. I used an external keyboard to switch TTYs, and the issue appears to be that the X server can't find any screens.

**Comment by mpfaff** [comment] 2020-08-26 04:04
Booting up again without `module_blacklist=amdgpu` results in a dark grey screen. I can't switch TTYs from it, but I can do Ctrl-Alt-Delete to reboot.

**Comment by mpfaff** [comment] 2020-08-26 14:36
I did some reading and confirmed that MacBooks with dedicated GPUs disable their integrated graphics at boot time for non-macOS operating systems.

Do you have any suggestions to debug the amdgpu module?

**Comment by JPyke3** [comment] 2020-08-27 02:36
Hi there,

I have noticed that there are a few new changes to be added to the kernel itself. I aim to work on this tonight. Will get to you guys soon.

**Comment by mpfaff** [comment] 2020-08-29 18:45
Do you think the blank screen issue might be related to https://github.com/marcosfad/mbp-ubuntu/issues/7?

**Comment by JPyke3** [comment] 2020-09-01 01:34
I'm unsure, I don't have this machine. But it could be related.

I pushed changes to https://github.com/JPyke3/linux57-mbp-manjaro to add the latest changes to the linux57 kernel. We can see if you have any more luck on that. If you are familiar with compiling the Kernel yourself then try those out.

If not I am currently compiling the kernel now. Unfortunatley my machine is rather slow and it takes me a few hours. It should be in my respository by this afternoon and ISO images should come out for it tonight. Let's see if we have more luck there :)

**Comment by JPyke3** [comment] 2020-09-04 21:36
Hi guys, still working on this sorry for the delay, had a few signing issues. Hoping to have it up soon as I have a day off today

**Comment by JPyke3** [comment] 2020-09-06 11:41
Hi guys,

Iso is compiled, give it a spin for me and let you know how you get on [LINK](https://drive.google.com/file/d/1u2pJrsW9_DxK9lf_mP3D79X7B-cTE0JT/view?usp=sharing)

You can also find it in the `/dev/` folder in the google drive on the `README`

**Comment by mpfaff** [comment] 2020-09-10 22:14
Sorry for missing your replies! I'll give it a try and get back to you.

**Comment by mpfaff** [comment] 2020-09-11 02:48
It works!

**Comment by JPyke3** [comment] 2020-09-11 02:50
Very happy to hear!! All the images are being compiled as we speak and I'm hoping to have them up by tomorrow.

**Closed** 2020-09-24 01:58 UTC
Labels: bug
